#!/bin/sh
# -*- sh -*-
set -e

complain() {
    echo "### $@" > complaint
}

die() {
    test -f progress && cat progress
    rm progress
    complain "$@"
    exit 1
}

clear() {
    rm -f progress report testcase.{c,dve}
    echo "#### PASSED"
    echo
}

debris() {
    echo
    echo "#### TEST END"
    echo
    test -f progress && (cat progress; echo) || true
    test -f testcase.c && (nl -ba testcase.c; echo) || true
    test -f testcase.cpp && (nl -ba testcase.cpp; echo) || true
    test -f complaint && cat complaint || true
    rm -f testcase.{c,cpp} complaint progress
    echo
    echo "."
}

"$@"
